language: elm
elm:
  - 0.19.0

cache: npm

script:
  # Build the production version of the app
  - npm run build

deploy:
  provider: s3
  bucket: pub.mattmoriarity.com
  skip_cleanup: true
  acl: public_read
  local_dir: dist
